---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Bae different layouts/Bae different layouts.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/227193/articles/308389/master/file/figures/Bae%20different%20layouts/Bae%20different%20layouts.png"
    folder_url: "/users/227193/articles/308389/master/folder/figures/Bae different
      layouts"
